export const profileData = {
	profiles: [
		{
			username: 'benjamin.huamani',
			email: 'benjaminhuamani@upeu.edu.pe',
			first_name: 'Benjamin',
			middle_name: 'Daniel',
			last_name: 'Huamani',
			second_last_name: 'Bailon',
			code: '202010352',
			role: 'Estudiante',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
		},
		{
			username: 'paulo.huaman',
			email: 'paulohuaman@upeu.edu.pe',
			first_name: 'Paulo',
			middle_name: 'David',
			last_name: 'Huaman',
			second_last_name: 'Calderon',
			code: '202010398',
			role: 'Estudiante',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
		},
		{
			username: 'josue.diaz',
			email: 'josuediaz@upeu.edu.pe',
			first_name: 'Josue',
			middle_name: 'David',
			last_name: 'Diaz',
			second_last_name: 'Moran',
			code: '202010349',
			role: 'Estudiante',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
		},
		{
			username: 'ppp.ingsistemas',
			email: 'ppp.ingsistemas@upeu.edu.pe',
			first_name: 'David',
			middle_name: 'Benjamin',
			last_name: 'Reyna',
			second_last_name: 'Barreto',
			code: '202010349',
			role: 'Docente',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
		},
	],
};
