export const profileData = {
	profiles: [
		{
			username: 'benjamin.huamani',
			email: 'benjaminhuamani@upeu.edu.pe',
			first_name: 'Benjamin',
			middle_name: 'Daniel',
			last_name: 'Huamani',
			second_last_name: 'Bailon',
			code: '202010352',
			role: 'Practicante',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
			phone: '987654321',
			avatar_url: 'https://ui-avatars.com/api/?size=225&name=benjamin+huamani',
		},
		{
			username: 'paulo.huaman',
			email: 'paulohuaman@upeu.edu.pe',
			first_name: 'Paulo',
			middle_name: 'David',
			last_name: 'Huaman',
			second_last_name: 'Calderon',
			code: '202010398',
			role: 'Practicante',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
			phone: '987654321',
			avatar_url: 'https://ui-avatars.com/api/?size=225&name=paulo+huaman',
		},
		{
			username: 'josue.diaz',
			email: 'josuediaz@upeu.edu.pe',
			first_name: 'Josue',
			middle_name: 'David',
			last_name: 'Diaz',
			second_last_name: 'Moran',
			code: '202010349',
			role: 'Practicante',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
			phone: '987654321',
			avatar_url: 'https://ui-avatars.com/api/?size=225&name=josue+diaz',
		},
		{
			username: 'ppp.ingsistemas',
			email: 'ppp.ingsistemas@upeu.edu.pe',
			first_name: 'David',
			middle_name: 'Benjamin',
			last_name: 'Reyna',
			second_last_name: 'Barreto',
			code: '202010349',
			role: 'Administrador',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
			phone: '987654321',
			avatar_url: 'https://ui-avatars.com/api/?size=225&name=ppp+ingsistemas',
		},
		{
			username: 'sec_eapsistemas',
			email: 'sec_eapsistemas@upeu.edu.pe',
			password: '$2b$10$ChpXgoUe5aCjokCEQq8lIOcTYlnXgL59NQnw7ZpH75SClf4KAmtpi',
			first_name: 'Jane',
			middle_name: 'Mary',
			last_name: 'Smith',
			second_last_name: 'Doe',
			code: '202010349',
			role: 'Secretaria',
			avatar_url: 'https://ui-avatars.com/api/?size=225&name=sec+eapsistemas',
			phone: '987654321',
		},
	],
};
